// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwljiqkipjzejtnkcnes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3bGppcWtpcGp6ZWp0bmtjbmVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTg2MzksImV4cCI6MjA3NDI5NDYzOX0.ylKFbqTdBqXySHfHWwVLexC779Mu3aO4X1I0q3CCM70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});